config/routes.rb
Rails.application.routes.draw do
  resources :karyawans

end

app/models/karyawan.rb
class Karyawan < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/karyawans_controller.rb
class KaryawansController < ApplicationController
  before_action :set_karyawan, only: [:show, :edit, :update, :destroy]

  # GET /karyawans
  # GET /karyawans.json
  def index
    @karyawans = Karyawan.all
  end

  # GET /karyawans/1
  # GET /karyawans/1.json
  def show
  end

  # GET /karyawans/new
  def new
    @karyawan = Karyawan.new
  end

  # GET /karyawans/1/edit
  def edit
  end

  # POST /karyawans
  # POST /karyawans.json
  def create
    @karyawan = Karyawan.new(karyawan_params)

    respond_to do |format|
      if @karyawan.save
        format.html { redirect_to @karyawan, notice: 'Karyawan was successfully created.' }
        format.json { render :show, status: :created, location: @karyawan }
      else
        format.html { render :new }
        format.json { render json: @karyawan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /karyawans/1
  # PATCH/PUT /karyawans/1.json
  def update
    respond_to do |format|
      if @karyawan.update(karyawan_params)
        format.html { redirect_to @karyawan, notice: 'Karyawan was successfully updated.' }
        format.json { render :show, status: :ok, location: @karyawan }
      else
        format.html { render :edit }
        format.json { render json: @karyawan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /karyawans/1
  # DELETE /karyawans/1.json
  def destroy
    @karyawan.destroy
    respond_to do |format|
      format.html { redirect_to karyawans_url, notice: 'Karyawan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_karyawan
      @karyawan = Karyawan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def karyawan_params
      params.require(:karyawan).permit(:nip, :nama, :alamat)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/karyawans_helper.rb
module KaryawansHelper
end

app/views/karyawans/_form.html.erb
<%= form_for(@karyawan) do |f| %>
  <% if @karyawan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@karyawan.errors.count, "error") %> prohibited this karyawan from being saved:</h2>

      <ul>
      <% @karyawan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nip %><br>
    <%= f.text_field :nip %>
  </div>
  <div class="field">
    <%= f.label :nama %><br>
    <%= f.text_field :nama %>
  </div>
  <div class="field">
    <%= f.label :alamat %><br>
    <%= f.text_area :alamat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/karyawans/edit.html.erb
<h1>Editing Karyawan</h1>

<%= render 'form' %>

<%= link_to 'Show', @karyawan %> |
<%= link_to 'Back', karyawans_path %>

app/views/karyawans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Karyawans</h1>

<table>
  <thead>
    <tr>
      <th>Nip</th>
      <th>Nama</th>
      <th>Alamat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @karyawans.each do |karyawan| %>
      <tr>
        <td><%= karyawan.nip %></td>
        <td><%= karyawan.nama %></td>
        <td><%= karyawan.alamat %></td>
        <td><%= link_to 'Tampilkan Data', karyawan %></td>
        <td><%= link_to 'Ubah', edit_karyawan_path(karyawan) %></td>
        <td><%= link_to 'Hapus', karyawan, method: :delete, data: { confirm: 'Apakah anda akan menghapus ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Tambah Data Karyawan', new_karyawan_path %>

app/views/karyawans/new.html.erb
<h1>New Karyawan</h1>

<%= render 'form' %>

<%= link_to 'Kembali', karyawans_path %>

app/views/karyawans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nip:</strong>
  <%= @karyawan.nip %>
</p>

<p>
  <strong>Nama:</strong>
  <%= @karyawan.nama %>
</p>

<p>
  <strong>Alamat:</strong>
  <%= @karyawan.alamat %>
</p>

<%= link_to 'Ubah', edit_karyawan_path(@karyawan) %> |
<%= link_to 'Kembali', karyawans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>